### PR TITLE
Missing step in '?' grammar

### PR DESCRIPTION
**Pull request by Pandetthe**

### CODE REVIEW

**Comment by odinserj** [comment]
Please share an example expression that isn't covered by the grammar.

**Comment by Pandetthe** [comment]
?/2 * * * *

**Comment by Pandetthe** [comment]
In readme '?' is described as "? is synonym of *", but in the grammar '?' don't allow step, that is working in CronExpression.Parse

**Comment by Pandetthe** [comment]
And there is a second problem with grammar, that step isn't in brackets [], so '*' is invalid but '*/2' is valid.

**Comment by odinserj** [comment]
You are totally correct, we also need to wrap it with `[]` in both cases.

**Review by odinserj — APPROVED** [review]

**Comment by odinserj** [comment]
Thanks a lot @Pandetthe! I've also moved them closer to the `*` character.

**Pull request merged**
